/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2020-03-21 06:57:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ex4;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class searchMapNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=d24b45a0cda3b0e29fc1ea1a3fa5d8f1&libraries=services\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function(){\r\n");
      out.write("\t// ë§ì»¤ë¥¼ í´ë¦­íë©´ ì¥ìëªì íì¶í  ì¸í¬ìëì° ìëë¤\r\n");
      out.write("\tvar infowindow = new kakao.maps.InfoWindow({zIndex:1});\r\n");
      out.write("\r\n");
      out.write("\tvar mapContainer = document.getElementById('map'), // ì§ëë¥¼ íìí  div \r\n");
      out.write("\t    mapOption = {\r\n");
      out.write("\t        center: new kakao.maps.LatLng(37.566826, 126.9786567), // ì§ëì ì¤ì¬ì¢í\r\n");
      out.write("\t        level: 3 // ì§ëì íë ë ë²¨\r\n");
      out.write("\t    };  \r\n");
      out.write("\t\r\n");
      out.write("\t//ë§ì»¤ëª©ë¡ì ë´ìë ë°°ì´ì ë§ë¤ì´ì.\r\n");
      out.write("\tvar markerList = [];\r\n");
      out.write("\r\n");
      out.write("\t// ì§ëë¥¼ ìì±í©ëë¤    \r\n");
      out.write("\tvar map = new kakao.maps.Map(mapContainer, mapOption); \r\n");
      out.write("\r\n");
      out.write("\t// ì¥ì ê²ì ê°ì²´ë¥¼ ìì±í©ëë¤\r\n");
      out.write("\tvar ps = new kakao.maps.services.Places(); \r\n");
      out.write("\r\n");
      out.write("\t// í¤ìëë¡ ì¥ìë¥¼ ê²ìí©ëë¤\r\n");
      out.write("\tps.keywordSearch('ì´íì ë§ì§', placesSearchCB); \r\n");
      out.write("\r\n");
      out.write("\t// í¤ìë ê²ì ìë£ ì í¸ì¶ëë ì½ë°±í¨ì ìëë¤\r\n");
      out.write("\tfunction placesSearchCB (data, status, pagination) {\r\n");
      out.write("\t    if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\r\n");
      out.write("\t        // ê²ìë ì¥ì ìì¹ë¥¼ ê¸°ì¤ì¼ë¡ ì§ë ë²ìë¥¼ ì¬ì¤ì íê¸°ìí´\r\n");
      out.write("\t        // LatLngBounds ê°ì²´ì ì¢íë¥¼ ì¶ê°í©ëë¤\r\n");
      out.write("\t        var bounds = new kakao.maps.LatLngBounds();\r\n");
      out.write("\r\n");
      out.write("\t        for (var i=0; i<data.length; i++) {\r\n");
      out.write("\t            displayMarker(data[i]);    \r\n");
      out.write("\t            bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));\r\n");
      out.write("\t        }       \r\n");
      out.write("\r\n");
      out.write("\t        // ê²ìë ì¥ì ìì¹ë¥¼ ê¸°ì¤ì¼ë¡ ì§ë ë²ìë¥¼ ì¬ì¤ì í©ëë¤\r\n");
      out.write("\t        map.setBounds(bounds);\r\n");
      out.write("\t    } \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// ì§ëì ë§ì»¤ë¥¼ íìíë í¨ììëë¤\r\n");
      out.write("\tfunction displayMarker(place) {\r\n");
      out.write("\t    \r\n");
      out.write("\t    // ë§ì»¤ë¥¼ ìì±íê³  ì§ëì íìí©ëë¤\r\n");
      out.write("\t    var marker = new kakao.maps.Marker({\r\n");
      out.write("\t        map: map,\r\n");
      out.write("\t        position: new kakao.maps.LatLng(place.y, place.x) \r\n");
      out.write("\t    });\r\n");
      out.write("\t    \r\n");
      out.write("\t    markerList.push(marker);\r\n");
      out.write("\r\n");
      out.write("\t    // ë§ì»¤ì í´ë¦­ì´ë²¤í¸ë¥¼ ë±ë¡í©ëë¤\r\n");
      out.write("\t    kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("\t        // ë§ì»¤ë¥¼ í´ë¦­íë©´ ì¥ìëªì´ ì¸í¬ìëì°ì íì¶ë©ëë¤\r\n");
      out.write("\t        infowindow.setContent('<div style=\"padding:5px;font-size:12px;\">' + place.place_name + '</div>');\r\n");
      out.write("\t        infowindow.open(map, marker);\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"btnSearch\").onclick = function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0; i<markerList.length; i++){\r\n");
      out.write("\t\t\tmarkerList[i].setMap(null); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar searchPlace = document.getElementById(\"place\").value;\r\n");
      out.write("\t\t// ì¥ì ê²ì ê°ì²´ë¥¼ ìì±í©ëë¤\r\n");
      out.write("\t\tvar ps = new kakao.maps.services.Places(); \r\n");
      out.write("\r\n");
      out.write("\t\t// í¤ìëë¡ ì¥ìë¥¼ ê²ìí©ëë¤\r\n");
      out.write("\t\tps.keywordSearch(searchPlace, placesSearchCB); \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>ì¥ì ê²ì</h2>\r\n");
      out.write("<input type=\"search\" id=\"place\">\r\n");
      out.write("<button id=\"btnSearch\">ê²ì</button>\r\n");
      out.write("\t<div id=\"map\" style=\"width:100%;height:350px;\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
